### ISSUE TITLE
can slide off ledges right after getting up from wall

### ISSUE THREAD

**Issue by RamenNoodles452** [RamenNoodles452/ProjectStealth#26]
I've been able to hold right when climbing a left wall and transitioning to the ground
and by holding right sometimes I slide off the wall

![](https://cdn.discordapp.com/attachments/465208959259901952/481684518001049602/unknown.png)
so this is me against the wall

![](https://cdn.discordapp.com/attachments/465208959259901952/481684633839337482/unknown.png)
this is where I end up after getting up from the wall

![](https://cdn.discordapp.com/attachments/465208959259901952/481684837401362432/unknown.png)
this is me holding right
sometimes i just completely slide off the wall

**Comment by JesterInBlack** [comment]
This should be resolved by the animation offset changes from pull #28. Confirmed no repro in master. Closing.
